### PR TITLE
Minor optimization

### PR DESCRIPTION
**Pull request by valera-rozuvan**
Skip `type == 'string'` condition check if **val** is not of type **String**.

### CODE REVIEW

**Comment by auraz** [comment]
@z4y4ts ^^

**Comment by valera-rozuvan** [comment]
@z4y4ts Updated my PR.

**Comment by z4y4ts** [comment]
Now it looks good.
Can you please change PR to merge into `dev` branch? We do all development there.

**Comment by valera-rozuvan** [comment]
@z4y4ts Done. Please see new PR https://github.com/raccoongang/xblock-video/pull/74 .

**Pull request closed without merging**
